version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ordens
      POSTGRES_DB: ordens_db
    ports:
      - "5433:5432"

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db